Add form cache
akai-org/generator-wnioskow-2022 pull request #7
Opened 2022-10-02 21:41 UTC by ziutech

Adds saving input values to localstorage and restoring them from localstorage on page reload

2022-10-02 21:55 UTC, krychaxp commented on src/components/Form/Form.tsx
> +  useEffect(() => {
Use external library (for example, react-use useLocalStorage)

2022-10-02 21:55 UTC, krychaxp commented on src/components/Form/Form.tsx
> +          setValue(name as InputNames, value as string);
Don't use "as string"

2022-10-03 08:51 UTC, Safeheaded commented on src/components/Form/Form.tsx
> +type InputNames =
Zamiast oddzielnie definiować całkowicie nowy typ, lepiej zrobić `type InputNames = keyof SchemaType;`. Wtedy automatycznie wszystkie nazwy pół wyciągnie z już istniejącego interfejsu i nie trzeba będzie zmieniać dwa razy - mniejsza szansa na bug'a w przyszłości

2022-10-03 11:39 UTC, Safeheaded requested changes
Dobrze by było też od razu dodać jakiś przycisk, który resetuje localStorage. Nie musi być na razie łatwy, byleby tylko była taka opcja

2022-10-03 16:35 UTC, Safeheaded approved these changes

2022-10-03 16:40 UTC, merged